Repository openshift/pipelines-tutorial, pull requests merged in 2019-12, with the labels that each got.

#41 Update tutorial
  README.md
  demo
  images/application-deployed.png
  images/console-import-yaml-2.png
  images/operator-install-1.png
  images/operator-install-2.png
  images/operator-install-3.png
  images/operator-install-4.png
  images/petclinic-deployed-1.png
  images/petclinic-deployed-2.png
  images/pipeline-details.png
  images/pipeline-diagram.png
  images/pipeline-diagram.svg
  petclinic/manifests.yaml
  pipeline/01-build-deploy.yaml
  pipeline/02-resources.yaml
  pipeline/03-pipelinerun.yaml
  pipeline/apply_manifest_task.yaml
  pipeline/pipeline.yaml
  pipeline/pipelinerun.yaml
  pipeline/resources.yaml
  pipeline/update_deployment_task.yaml
Labels: approved, lgtm, size/XL

#43 Minor improvement to computing route url
  README.md
  demo
Labels: approved, size/XS

#44 Add Piyush to Approvers
  OWNERS_ALIASES
Labels: approved, size/XS

#45 Refactor url function
  demo
Labels: approved, size/XS

#48 Fix CLI installation link
  README.md
Labels: approved, lgtm, size/XS

#52 Add note about resources if using different namespace
  README.md
Labels: approved, lgtm, size/XS

#49 Updated screenshots
  README.md
  images/application-deployed.png
  images/console-import-yaml-1.png
  images/console-import-yaml-2.png
  images/console-import-yaml.png
  images/developer.png
  images/operatorhub.png
  images/projects.png
Labels: approved, lgtm, size/S

#54 Fix tutorial bugs
  pipeline/apply_manifest_task.yaml
Labels: approved, lgtm, size/XS
