Repository openshift/pipelines-tutorial, pull requests merged in 2019-10, with the labels that each got.

#24 Separate pipeline manifest from the app manifests
  README.md
  demo
  petclinic/manifests.yaml
  pipeline/01-build-deploy.yaml
  pipeline/02-resources.yaml
  pipeline/03-pipelinerun.yaml
Labels: size/M

#23 0.7 release: update doc and demo
  README.md
  demo
Labels: size/M

#25 Updated task refs to catalog 0.7
  README.md
  demo
Labels: lgtm, size/S

#26 Updated pipeline with new array arg type
  pipeline/01-build-deploy.yaml
Labels: lgtm, size/XS

#27 Added instructions to adjust the service account permissions
  README.md
  demo
Labels: lgtm, size/XS

#28 Updated task refs for tutorial release-v0.5
  README.md
  demo
Labels: lgtm, needs-rebase, size/XS

#31 Added instructions for using the dev console for starting pipelines
  README.md
Labels: lgtm, size/XS

#30 Revert "Added instrutions to adjust the service account permissions"
  README.md
  demo
Labels: size/XS

#32 Removed privileged default sa for dev console
  README.md
Labels: size/XS

#34 Removed trigger field
  pipeline/03-pipelinerun.yaml
Labels: lgtm, size/XS
