Repository openshift/pipelines-tutorial, pull requests merged in 2019-08, with the labels that each got.

#13 demo script to run everything quickly
  demo
Labels: lgtm, size/M

#14 fixing typo
  README.md
Labels: size/XS

#16 Added help print for demo script
  .gitignore
  demo
Labels: lgtm, size/S

#17 Updated tutorial with latest tkn commands
  README.md
Labels: lgtm, size/S
