Repository openshift/pipelines-tutorial, pull requests merged in 2019-07, with the labels that each got.

#7 Editing Pipelines Tutorial Documentation
  README.md
  install-operator.md
Labels: lgtm, size/M

#9 Add initialDelaySeconds and Increase Readiness Probe timeoutSeconds
  resources/petclinic.yaml
Labels: lgtm, size/XS

#10 Add oc create Commands that Reference YAML Files Under Resources
  README.md
Labels: lgtm, size/M

#12 Updated tutorial with new operator flow and CLI commands
  README.md
  images/operator-install-2.png
  images/operator-install-3.png
  images/operator-install-4.png
  images/operator-install-5.png
  images/operator-install-6.png
  images/operator-install-7.png
  install-operator.md
  resources/petclinic-deploy-pipeline.yaml
  resources/petclinic-deploy-pipelinerun.yaml
Labels: lgtm, size/L
