Repository openshift/pipelines-tutorial, pull requests merged in 2019-11, with the labels that each got.

#35 Update Tutorial for Openshift 4.2 and Pipelines 0.7.0
  README.md
  images/administrator.png
  images/console-import-yaml-1.png
  images/console-import-yaml-2.png
  images/developer.png
  images/operator-install-1.png
  images/operator-install-2.png
  images/operator-install-3.png
  images/operator-install-4.png
  images/operatorhub.png
  images/petclinic-deployed-1.png
  images/petclinic-deployed-2.png
  images/pipeline-details.png
  images/pipelines-operator.png
  images/projects.png
  install-operator.md
Labels: lgtm, size/L

#38 Add owner files
  OWNERS
  OWNERS_ALIASES
Labels: do-not-merge/invalid-owners-file, lgtm, size/S

#39 Fix links in release-0.5 branch
  README.md
Labels: lgtm, size/XS

#40 Fix links in release-v0.7 branch
  README.md
Labels: approved, size/XS
